### ISSUE TITLE
Issues regarding the dark theme of Blargmode

### ISSUE THREAD

**Issue by ErikThorsell** [SimonAlling/better-sweclockers#2] opened 2015-05-17 06:55 UTC
When reloading the webpage it will turn white before applying the theme. Nothing weird, I guess, since this is due to the fact that Better-Sweclockers must get some time to realize it's actually on sweclockers.com. However there are additional concerns with the theme:
- Not working at all on the profile settings page.
- Occasionally the dark theme will stop working between page loads on the actual site as well.

**Comment by SimonAlling** [comment] 2015-05-17 08:52
>When reloading the webpage it will turn white before applying the theme.

It is my understanding that this behavior is inherent to userscripting: The script runs at `document-start`, and I assume there is some period of time from the user pressing F5 to `document-start` actually occurring. Also, when it does, BSC must load saved settings before it can determine whether or not it should activate the dark theme: Activating it by default and then reverting to the standard theme would probably look just as bad when using the standard theme.

>However there are additional concerns with the theme:
>* Not working at all on the profile settings page.

This is not a bug, but an issue that was not foreseen when the code handling saving of settings was written. **HTML5 `localStorage` does not work across origins**, and `http://sweclockers.com` and `https://sweclockers.com` count as different origins. Since we save settings on HTTP, we cannot access them on HTTPS, and we cannot force either protocol. Therefore, I chose to simply not run BSC on HTTPS. However, searching the internet, we can see that [there may be a workaround](http://stackoverflow.com/a/10505907) using an `iframe` to save settings. I am going to look into this as soon as possible.

>* Occasionally the dark theme will stop working between page loads on the actual site as well.

Unless it is because you visit an HTTPS page, it could be because you have set an interval for the dark theme. Otherwise, please post the affected URL and any suspicious console messages.

**Comment by lindhe** [comment] 2016-08-05 20:49
Text fields on the BSC settings page are hard to read.

![screenshot from 2016-08-05 22-47-50](https://cloud.githubusercontent.com/assets/7773090/17450128/d03909d2-5b5e-11e6-96be-965d5158f6b0.png)

**Comment by lindhe** [comment] 2016-08-05 21:18
Blargmode does not have a repo, right?

**Comment by SimonAlling** [comment] 2018-08-10 18:28
He does. [I have submitted an issue.](/Blargmode/Sweclockers-Dark-Theme/issues/7)

I have also added [a hotfix for the unreadable text fields](/SimonAlling/better-sweclockers/commit/6513702d89668011cf517cf4fac6847325198a40), and I believe the other problems mentioned in this thread are not relevant anymore (because SweClockers use HTTPS across the board since [last year](https://www.sweclockers.com/artikel/24488-sweclockers-gar-over-till-https)), so I'm closing this issue.

**Closed by SimonAlling** 2018-08-10 18:28 UTC
